export const mainTableHeaders = [
  { id: 'address', label: 'Address' },
  { id: 'name', label: 'Name' },
  { id: 'slots', label: 'Slots' },
  { id: 'delete', label: 'Actions' },
];

export const secondaryTableHeaders = [
  { id: 'brand', label: 'Brand' },
  { id: 'year', label: 'Year' },
  { id: 'color', label: 'Color' },
];

export const secondaryTableData = [
  { id: 1, brand: 'Volvo', year: '2002', color: 'red' },
  { id: 2, brand: 'BMW', year: '2010', color: 'blue' },
  { id: 3, brand: 'Audi', year: '2015', color: 'green' },
  { id: 4, brand: 'Toyota', year: '2008', color: 'yellow' },
  { id: 5, brand: 'Ford', year: '2012', color: 'orange' },
  { id: 6, brand: 'Honda', year: '2018', color: 'purple' },
  { id: 7, brand: 'Nissan', year: '2005', color: 'pink' },
  { id: 8, brand: 'Mazda', year: '2011', color: 'brown' },
  { id: 9, brand: 'Chevrolet', year: '2014', color: 'cyan' },
  { id: 10, brand: 'Kia', year: '2009', color: 'magenta' },
  { id: 11, brand: 'Volvo', year: '2003', color: 'red' },
  { id: 12, brand: 'BMW', year: '2011', color: 'blue' },
  { id: 13, brand: 'Audi', year: '2016', color: 'green' },
  { id: 14, brand: 'Toyota', year: '2007', color: 'yellow' },
  { id: 15, brand: 'Ford', year: '2013', color: 'orange' },
  { id: 16, brand: 'Honda', year: '2019', color: 'purple' },
  { id: 17, brand: 'Nissan', year: '2006', color: 'pink' },
  { id: 18, brand: 'Mazda', year: '2012', color: 'brown' },
  { id: 19, brand: 'Chevrolet', year: '2015', color: 'cyan' },
  { id: 20, brand: 'Kia', year: '2010', color: 'magenta' },
  { id: 21, brand: 'Volvo', year: '2004', color: 'red' },
  { id: 22, brand: 'BMW', year: '2012', color: 'blue' },
  { id: 23, brand: 'Audi', year: '2017', color: 'green' },
  { id: 24, brand: 'Toyota', year: '2006', color: 'yellow' },
  { id: 25, brand: 'Ford', year: '2014', color: 'orange' },
  { id: 26, brand: 'Honda', year: '2020', color: 'purple' },
  { id: 27, brand: 'Nissan', year: '2007', color: 'pink' },
  { id: 28, brand: 'Mazda', year: '2013', color: 'brown' },
  { id: 29, brand: 'Chevrolet', year: '2016', color: 'cyan' },
  { id: 30, brand: 'Kia', year: '2011', color: 'magenta' },
  { id: 31, brand: 'Volvo', year: '2005', color: 'red' },
  { id: 32, brand: 'BMW', year: '2013', color: 'blue' },
  { id: 33, brand: 'Audi', year: '2018', color: 'green' },
  { id: 34, brand: 'Toyota', year: '2005', color: 'yellow' },
  { id: 35, brand: 'Ford', year: '2015', color: 'orange' },
  { id: 36, brand: 'Honda', year: '2021', color: 'purple' },
  { id: 37, brand: 'Nissan', year: '2008', color: 'pink' },
  { id: 38, brand: 'Mazda', year: '2014', color: 'brown' },
  { id: 39, brand: 'Chevrolet', year: '2017', color: 'cyan' },
  { id: 40, brand: 'Kia', year: '2012', color: 'magenta' },
  { id: 41, brand: 'Volvo', year: '2006', color: 'red' },
  { id: 42, brand: 'BMW', year: '2014', color: 'blue' },
  { id: 43, brand: 'Audi', year: '2019', color: 'green' },
  { id: 44, brand: 'Toyota', year: '2004', color: 'yellow' },
  { id: 45, brand: 'Ford', year: '2016', color: 'orange' },
  { id: 46, brand: 'Honda', year: '2022', color: 'purple' },
  { id: 47, brand: 'Nissan', year: '2009', color: 'pink' },
  { id: 48, brand: 'Mazda', year: '2015', color: 'brown' },
  { id: 49, brand: 'Chevrolet', year: '2018', color: 'cyan' },
  { id: 50, brand: 'Kia', year: '2013', color: 'magenta' },
  { id: 51, brand: 'Volvo', year: '2007', color: 'red' },
  { id: 52, brand: 'BMW', year: '2015', color: 'blue' },
  { id: 53, brand: 'Audi', year: '2020', color: 'green' },
  { id: 54, brand: 'Toyota', year: '2003', color: 'yellow' },
];
