import { CarColors } from '~/types/TableProps';

export const mainTableHeaders = [
  { id: 'address', label: 'Address' },
  { id: 'name', label: 'Name' },
  { id: 'slots', label: 'Slots' },
  { id: 'delete', label: 'Actions' },
];

export const secondaryTableHeaders = [
  { id: 'brand', label: 'Brand' },
  { id: 'year', label: 'Year' },
  { id: 'color', label: 'Color' },
];

export const secondaryTableData = [
  { id: 1, brand: 'Volvo', year: '2002', color: CarColors.Red },
  { id: 2, brand: 'BMW', year: '2010', color: CarColors.Blue },
  { id: 3, brand: 'Audi', year: '2015', color: CarColors.Green },
  { id: 4, brand: 'Toyota', year: '2008', color: CarColors.Yellow },
  { id: 5, brand: 'Ford', year: '2012', color: CarColors.Orange },
  { id: 6, brand: 'Honda', year: '2018', color: CarColors.Purple },
  { id: 7, brand: 'Nissan', year: '2005', color: CarColors.Pink },
  { id: 8, brand: 'Mazda', year: '2011', color: CarColors.Brown },
  { id: 9, brand: 'Chevrolet', year: '2014', color: CarColors.Cyan },
  { id: 10, brand: 'Kia', year: '2009', color: CarColors.Magenta },
  { id: 11, brand: 'Volvo', year: '2003', color: CarColors.Red },
  { id: 12, brand: 'BMW', year: '2011', color: CarColors.Blue },
  { id: 13, brand: 'Audi', year: '2016', color: CarColors.Green },
  { id: 14, brand: 'Toyota', year: '2007', color: CarColors.Yellow },
  { id: 15, brand: 'Ford', year: '2013', color: CarColors.Orange },
  { id: 16, brand: 'Honda', year: '2019', color: CarColors.Purple },
  { id: 17, brand: 'Nissan', year: '2006', color: CarColors.Pink },
  { id: 18, brand: 'Mazda', year: '2012', color: CarColors.Brown },
  { id: 19, brand: 'Chevrolet', year: '2015', color: CarColors.Cyan },
  { id: 20, brand: 'Kia', year: '2010', color: CarColors.Magenta },
  { id: 21, brand: 'Volvo', year: '2004', color: CarColors.Red },
  { id: 22, brand: 'BMW', year: '2012', color: CarColors.Blue },
  { id: 23, brand: 'Audi', year: '2017', color: CarColors.Green },
  { id: 24, brand: 'Toyota', year: '2006', color: CarColors.Yellow },
  { id: 25, brand: 'Ford', year: '2014', color: CarColors.Orange },
  { id: 26, brand: 'Honda', year: '2020', color: CarColors.Purple },
  { id: 27, brand: 'Nissan', year: '2007', color: CarColors.Pink },
  { id: 28, brand: 'Mazda', year: '2013', color: CarColors.Brown },
  { id: 29, brand: 'Chevrolet', year: '2016', color: CarColors.Cyan },
  { id: 30, brand: 'Kia', year: '2011', color: CarColors.Magenta },
  { id: 31, brand: 'Volvo', year: '2005', color: CarColors.Red },
  { id: 32, brand: 'BMW', year: '2013', color: CarColors.Blue },
  { id: 33, brand: 'Audi', year: '2018', color: CarColors.Green },
  { id: 34, brand: 'Toyota', year: '2005', color: CarColors.Yellow },
  { id: 35, brand: 'Ford', year: '2015', color: CarColors.Orange },
  { id: 36, brand: 'Honda', year: '2021', color: CarColors.Purple },
  { id: 37, brand: 'Nissan', year: '2008', color: CarColors.Pink },
  { id: 38, brand: 'Mazda', year: '2014', color: CarColors.Brown },
  { id: 39, brand: 'Chevrolet', year: '2017', color: CarColors.Cyan },
  { id: 40, brand: 'Kia', year: '2012', color: CarColors.Magenta },
  { id: 41, brand: 'Volvo', year: '2006', color: CarColors.Red },
  { id: 42, brand: 'BMW', year: '2014', color: CarColors.Blue },
  { id: 43, brand: 'Audi', year: '2019', color: CarColors.Green },
  { id: 44, brand: 'Toyota', year: '2004', color: CarColors.Yellow },
  { id: 45, brand: 'Ford', year: '2016', color: CarColors.Orange },
  { id: 46, brand: 'Honda', year: '2022', color: CarColors.Purple },
  { id: 47, brand: 'Nissan', year: '2009', color: CarColors.Pink },
  { id: 48, brand: 'Mazda', year: '2015', color: CarColors.Brown },
  { id: 49, brand: 'Chevrolet', year: '2018', color: CarColors.Cyan },
  { id: 50, brand: 'Kia', year: '2013', color: CarColors.Magenta },
  { id: 51, brand: 'Volvo', year: '2007', color: CarColors.Red },
  { id: 52, brand: 'BMW', year: '2015', color: CarColors.Blue },
  { id: 53, brand: 'Audi', year: '2020', color: CarColors.Green },
  { id: 54, brand: 'Toyota', year: '2003', color: CarColors.Yellow },
];
