export const mainTableHeaders = [
  { id: 'address', label: 'Address' },
  { id: 'name', label: 'Name' },
  { id: 'slots', label: 'Slots' },
  { id: 'delete', label: 'Actions' },
];

export const secondaryTableHeaders = [
  { id: 'brand', label: 'Brand' },
  { id: 'year', label: 'Year' },
  { id: 'color', label: 'Color' },
];

export const secondaryTableData = [
  { brand: 'Volvo', year: '2002', color: 'red' },
  { brand: 'BMW', year: '2010', color: 'blue' },
  { brand: 'Audi', year: '2015', color: 'green' },
  { brand: 'Toyota', year: '2008', color: 'yellow' },
  { brand: 'Ford', year: '2012', color: 'orange' },
  { brand: 'Honda', year: '2018', color: 'purple' },
  { brand: 'Nissan', year: '2005', color: 'pink' },
  { brand: 'Mazda', year: '2011', color: 'brown' },
  { brand: 'Chevrolet', year: '2014', color: 'cyan' },
  { brand: 'Kia', year: '2009', color: 'magenta' },
  { brand: 'Volvo', year: '2003', color: 'red' },
  { brand: 'BMW', year: '2011', color: 'blue' },
  { brand: 'Audi', year: '2016', color: 'green' },
  { brand: 'Toyota', year: '2007', color: 'yellow' },
  { brand: 'Ford', year: '2013', color: 'orange' },
  { brand: 'Honda', year: '2019', color: 'purple' },
  { brand: 'Nissan', year: '2006', color: 'pink' },
  { brand: 'Mazda', year: '2012', color: 'brown' },
  { brand: 'Chevrolet', year: '2015', color: 'cyan' },
  { brand: 'Kia', year: '2010', color: 'magenta' },
  { brand: 'Volvo', year: '2004', color: 'red' },
  { brand: 'BMW', year: '2012', color: 'blue' },
  { brand: 'Audi', year: '2017', color: 'green' },
  { brand: 'Toyota', year: '2006', color: 'yellow' },
  { brand: 'Ford', year: '2014', color: 'orange' },
  { brand: 'Honda', year: '2020', color: 'purple' },
  { brand: 'Nissan', year: '2007', color: 'pink' },
  { brand: 'Mazda', year: '2013', color: 'brown' },
  { brand: 'Chevrolet', year: '2016', color: 'cyan' },
  { brand: 'Kia', year: '2011', color: 'magenta' },
  { brand: 'Volvo', year: '2005', color: 'red' },
  { brand: 'BMW', year: '2013', color: 'blue' },
  { brand: 'Audi', year: '2018', color: 'green' },
  { brand: 'Toyota', year: '2005', color: 'yellow' },
  { brand: 'Ford', year: '2015', color: 'orange' },
  { brand: 'Honda', year: '2021', color: 'purple' },
  { brand: 'Nissan', year: '2008', color: 'pink' },
  { brand: 'Mazda', year: '2014', color: 'brown' },
  { brand: 'Chevrolet', year: '2017', color: 'cyan' },
  { brand: 'Kia', year: '2012', color: 'magenta' },
  { brand: 'Volvo', year: '2006', color: 'red' },
  { brand: 'BMW', year: '2014', color: 'blue' },
  { brand: 'Audi', year: '2019', color: 'green' },
  { brand: 'Toyota', year: '2004', color: 'yellow' },
  { brand: 'Ford', year: '2016', color: 'orange' },
  { brand: 'Honda', year: '2022', color: 'purple' },
  { brand: 'Nissan', year: '2009', color: 'pink' },
  { brand: 'Mazda', year: '2015', color: 'brown' },
  { brand: 'Chevrolet', year: '2018', color: 'cyan' },
  { brand: 'Kia', year: '2013', color: 'magenta' },
  { brand: 'Volvo', year: '2007', color: 'red' },
  { brand: 'BMW', year: '2015', color: 'blue' },
  { brand: 'Audi', year: '2020', color: 'green' },
  { brand: 'Toyota', year: '2003', color: 'yellow' },
];
